# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170424_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
