# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_useravatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user',
        ),
        migrations.AddField(
            model_name='useravatar',
            name='username',
            field=models.CharField(default=b'Unnamed User', max_length=250),
        ),
    ]
